import { NS } from "@/constants/ns";
import { TaskType } from "@/services/tasks/types";

import { BuyStars } from "./components/buy-stars/BuyStars";
import { CommonModal } from "./components/common-modal/CommonModal";
import { PromoteTon } from "./components/promote-ton/PromoteTon";
import { ModalProps } from "./types";

export const CHECK_TASKS_MODAL_TID = {
  [TaskType.TON_PROMOTE]: `${NS.PAGES.ASSIGNMENTS.MODALS.ROOT}.${NS.PAGES.ASSIGNMENTS.MODALS.CHECK_ASSIGNMENTS.ROOT}.${NS.PAGES.ASSIGNMENTS.MODALS.CHECK_ASSIGNMENTS.SUBSCRIBE_TO_CHANNEL}`,
  [TaskType.STORIES_REPLY]: `${NS.PAGES.ASSIGNMENTS.MODALS.ROOT}.${NS.PAGES.ASSIGNMENTS.MODALS.CHECK_ASSIGNMENTS.ROOT}.${NS.PAGES.ASSIGNMENTS.MODALS.CHECK_ASSIGNMENTS.SHARE_STORY}`,
  [TaskType.ADD_TO_HOME]: `${NS.PAGES.ASSIGNMENTS.MODALS.ROOT}.${NS.PAGES.ASSIGNMENTS.MODALS.CHECK_ASSIGNMENTS.ROOT}.${NS.PAGES.ASSIGNMENTS.MODALS.CHECK_ASSIGNMENTS.ADD_GAME}`,
  [TaskType.SOCIAL_SUB]: `${NS.PAGES.ASSIGNMENTS.MODALS.ROOT}.${NS.PAGES.ASSIGNMENTS.MODALS.CHECK_ASSIGNMENTS.ROOT}.${NS.PAGES.ASSIGNMENTS.MODALS.CHECK_ASSIGNMENTS.SUBSCRIBE_TO_CHANNEL}`,
  [TaskType.EMOJI_SET]: `${NS.PAGES.ASSIGNMENTS.MODALS.ROOT}.${NS.PAGES.ASSIGNMENTS.MODALS.CHECK_ASSIGNMENTS.ROOT}.${NS.PAGES.ASSIGNMENTS.MODALS.CHECK_ASSIGNMENTS.ADD_EMOJI_STATUS}`,
  [TaskType.DONATE]: `${NS.PAGES.ASSIGNMENTS.MODALS.ROOT}.${NS.PAGES.ASSIGNMENTS.MODALS.CHECK_ASSIGNMENTS.ROOT}.${NS.PAGES.ASSIGNMENTS.MODALS.CHECK_ASSIGNMENTS.BUY_STARS}`,
  [TaskType.WALLET_CONNECT]: `${NS.PAGES.ASSIGNMENTS.MODALS.ROOT}.${NS.PAGES.ASSIGNMENTS.MODALS.CHECK_ASSIGNMENTS.ROOT}.${NS.PAGES.ASSIGNMENTS.MODALS.CHECK_ASSIGNMENTS.SUBSCRIBE_TO_CHANNEL}`,
  [TaskType.BOOST_CHANNEL]: `${NS.PAGES.ASSIGNMENTS.MODALS.ROOT}.${NS.PAGES.ASSIGNMENTS.MODALS.CHECK_ASSIGNMENTS.ROOT}.${NS.PAGES.ASSIGNMENTS.MODALS.CHECK_ASSIGNMENTS.DO_ASSIGNMENT}`,
};

export const VERIFIED_TYPES = [TaskType.TON_PROMOTE];

export const COMPONENTS_MAP: Record<
  TaskType,
  React.FC<React.PropsWithChildren<ModalProps>>
> = {
  [TaskType.DONATE]: BuyStars,
  [TaskType.STORIES_REPLY]: CommonModal,
  [TaskType.ADD_TO_HOME]: CommonModal,
  [TaskType.SOCIAL_SUB]: CommonModal,
  [TaskType.EMOJI_SET]: CommonModal,
  [TaskType.WALLET_CONNECT]: CommonModal,
  [TaskType.BOOST_CHANNEL]: CommonModal,
  [TaskType.TON_PROMOTE]: PromoteTon,
};
