export const NS = {
  COMMON: {
    ROOT: "COMMON",
    LOCALE_SWITCHER: {
      ROOT: "LOCALE_SWITCHER",
      RUSSIAN: "RUSSIAN",
      ENGLISH: "ENGLISH",
    },
    ROUTES: {
      ROOT: "ROUTES",
      SETTINGS: "SETTINGS",
    },
    TOAST: {
      ROOT: "TOAST",
      DESTRUCTIVE: "DESTRUCTIVE",
      DONE: "DONE",
      WARNING: "WARNING",
      UPDATE_TELEGRAM: "UPDATE_TELEGRAM",
    },
    OK: "OK",
    BUY: "BUY",
    SALE: "SALE",
    STARS: "STARS",
    TAP_TO_CONTINUE: "TAP_TO_CONTINUE"
  },
  PAGES: {
    HOME: {
      ROOT: "HOME",
      OFFLINE_BONUS: {
        ROOT: "OFFLINE_BONUS",
        TITLE: "TITLE",
        DESCRIPTION: "DESCRIPTION",
        GET_BONUS: "GET_BONUS",
        BUY_BONUS: "BUY_BONUS",
      },
    },
    SETTINGS: {
      ROOT: "SETTINGS",
      WALLET: {
        ROOT: "WALLET",
        TITLE: "TITLE",
        CONNECT_WALLET: "CONNECT",
      },
      BALANCE: {
        ROOT: "BALANCE",
        TITLE: "TITLE",
        STARS: "STARS",
        FRIENDS: "FRIENDS",
        TON: "TON",
      },
      GENERAL_SETTINGS: {
        ROOT: "GENERAL_SETTINGS",
        TITLE: "TITLE",
        SOUND: "SOUND",
        VIBRATIONS: "VIBRATIONS",
      },
      ABOUT_THE_APP: {
        ROOT: "ABOUT_THE_APP",
        TITLE: "TITLE",
        RULES: "RULES",
        SUPPORT: "SUPPORT",
      },
      COMMUNITY: {
        ROOT: "COMMUNITY",
        TITLE: "TITLE",
        SUBSCRIBE: "SUBSCRIBE",
        LEARN_MORE: "LEARN_MORE",
      },
      LANGUAGE: {
        ROOT: "LANGUAGE",
        TITLE: "TITLE",
      },
      DISCONNECT_MODAL: {
        ROOT: "DISCONNECT_MODAL",
        TITLE: "TITLE",
        DESCRIPTION: "DESCRIPTION",
        AGGREEMENT: "AGGREEMENT",
        BUTTON: "BUTTON",
      },
    },
    ASSIGNMENTS: {
      ROOT: "ASSIGNMENTS",
      HEADER: {
        ROOT: "HEADER",
        BALANCE: {
          ROOT: "BALANCE",
          TITLE: "TITLE",
          STARS: "STARS",
          FRIENDS: "FRIENDS",
        },
      },
      TYPES: {
        ROOT: "TYPES",
        DAILY: "DAILY",
        ONE_OFF: "ONE_OFF",
      },
      MODALS: {
        ROOT: "MODALS",
        CHECK_ASSIGNMENTS: {
          ROOT: "CHECK_ASSIGNMENTS",
          DO_ASSIGNMENT: "DO_ASSIGNMENT",
          BUTTON: "BUTTON",
          SUBSCRIBE_TO_CHANNEL: "SUBSCRIBE_TO_CHANNEL",
          SHARE_STORY: "SHARE_STORY",
          ADD_GAME: "ADD_GAME",
          ADD_EMOJI_STATUS: "ADD_EMOJI_STATUS",
          BUY_STARS: "BUY_STARS",
          CHECK_ASSIGNMENTS: "CHECK_ASSIGNMENTS",
          WALLET_CONNECT: "WALLET_CONNECT",
          MAKE_TRANSACTION: "MAKE_TRANSACTION",
        },
        CONFIRMATION_MODAL: {
          ROOT: "CONFIRMATION_MODAL",
          TITLE: "TITLE",
          DESCRIPTION: "DESCRIPTION",
          AWARD: "AWARD",
          PENALTY: "PENALTY",
          BUTTON: "BUTTON",
          DOUBLE_CHECK: "DOUBLE_CHECK",
        },
      },
    },
    BATTLE_PASS: {
      ROOT: "BATTLE_PASS",
      BUTTONS: {
        ROOT: "BUTTONS",
        IMPROVE: "IMPROVE",
        COLLECT: "COLLECT",
      },
    },
    FRIENDS: {
      ROOT: "FRIENDS",
      TITLE: "TITLE",
      PROPOSAL: "PROPOSAL",
      INVITE_FRIEND: "INVITE_FRIEND",
      INVITE_DESCRIPTION: "INVITE_DESCRIPTION",
      INVITE_BUTTON_TEXT: "INVITE_BUTTON_TEXT",
      INVITED: "INVITED",
      COLLECT_PRIZE: "COLLECT_PRIZE",
      LINK_COPIED: "LINK_COPIED",
      PROFIT: "PROFIT",
      GET: "GET",
      GET_FRIENDS: "GET_FRIENDS",
      CAN_COLLECT: "CAN_COLLECT",
      MODAL: {
        ROOT: "MODAL",
        TITLE: "TITLE",
        DESCRIPTION: "DESCRIPTION",
        BUTTON: "BUTTON",
        SALE: "SALE",
        FRIENDS: "FRIENDS",
        BOUGHT_SUCCESSFULLY: "BOUGHT_SUCCESSFULLY",
      },
      ERRORS: {
        ROOT: "ERRORS",
        BUY_FRIENDS: "BUY_FRIENDS",
      },
    },
    REWARDS: {
      ROOT: "REWARDS",
      GET_REWARDS: "GET_REWARDS",
      TABS: {
        ROOT: "TABS",
        EARNINGS: "EARNINGS",
        REWARDS: "REWARDS",
        BOOSTERS: "BOOSTERS",
      },
      BOOSTERS: {
        ROOT: "BOOSTERS",
        PREMIUM: "PREMIUM",
        AVAILABLE: "AVAILABLE",
        NOT_AVAILABLE: "NOT_AVAILABLE",
        APPLY: "APPLY",
        BUY: "BUY",
        COUNT: "COUNT",
        LEVEL: "LEVEL",
        EVERYDAY: "EVERYDAY",
        DEFAULT: "DEFAULT",
        ENERGY_BOOSTERS: "ENERGY_BOOSTERS",
        FULL_ENERGY: "FULL_ENERGY",
        RECOVERY_ENERGY: "RECOVERY_ENERGY",
        TITLE: "TITLE",
        ENERGY: "ENERGY",
        SUCCESS_BUY_BOOSTER: "SUCCESS_BUY_BOOSTER",
        SUCCESS_APPLY_BOOSTER: "SUCCESS_APPLY_BOOSTER",
        COUNT_BOOSTERS: "COUNT_BOOSTERS",
        BUY_FOR: "BUY_FOR",
        MULTIPLE_TEMP_ENERGY: "MULTIPLE_TEMP_ENERGY",
        TEMP_ENERGY: "TEMP_ENERGY",
        MODAL_TITLE: "MODAL_TITLE",
        INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
      },
      EVENTS: {
        ROOT: "EVENTS",
        TITLE: "TITLE",
        EVENT_AGENCY: "EVENT_AGENCY",
        LEADER_OF_MINDS: "LEADER_OF_MINDS",
        TAXI: "TAXI",
        INVITE_FRIENDS: "INVITE_FRIENDS",
        LEVEL: "LEVEL",
        EVENTS_LIST: {
          ROOT: "EVENTS_LIST",
          STARSBANK: "STARSBANK",
          OILCOMPANY: "OILCOMPANY",
          GREENENERGY: "GREENENERGY",
          CHARGINGSTATION: "CHARGINGSTATION",
          PSYCHOLOGIST: "PSYCHOLOGIST",
          SUCCESSFULTRADING: "SUCCESSFULTRADING",
          BARBERSHOP: "BARBERSHOP",
          STREAMER: "STREAMER",
          COMPUTERCLUB: "COMPUTERCLUB",
          GAMECOMPANY: "GAMECOMPANY",
          SHOP: "SHOP",
          FOODDELIVERY: "FOODDELIVERY",
          RESTAURANT: "RESTAURANT",
          EDUCATIONALCOURSES: "EDUCATIONALCOURSES",
          CYBERSECURITY: "CYBERSECURITY",
          STARLINK: "STARLINK",
          STARTUP: "STARTUP",
          ELECTICALCOMMERCY: "ELECTICALCOMMERCY",
          SOCIALNETWORKS: "SOCIALNETWORKS",
          BLOGGING: "BLOGGING",
          PODCASTER: "PODCASTER",
          OPINIONLEADER: "OPINIONLEADER",
          CONFERENCE: "CONFERENCE",
          HOTEL: "HOTEL",
          AUTOSALON: "AUTOSALON",
          TAXI: "TAXI",
        },
      },
      TOASTS: {
        ROOT: "TOASTS",
        FULL_ENERGY: "FULL_ENERGY",
        NOT_AVAILABLE: "NOT_AVAILABLE",
      },
    },
    HEROES: {
      ROOT: "HEROES",
      TITLE: "TITLE",
      LABELS: {
        ROOT: "LABELS",
        GET: "GET",
        BUY: "BUY",
        SELECT: "SELECT",
        SELECTED: "SELECTED",
        GO_TO_SHOP: "GO_TO_SHOP",
        ENERGY: "ENERGY",
        INCOME_PER_HOUR: "INCOME_PER_HOUR",
        INCOME_PER_TAP: "INCOME_PER_TAP",
        UNITS: {
          ROOT: "UNITS",
          ENERGY: "ENERGY",
          INCOME_PER_HOUR: "INCOME_PER_HOUR",
          INCOME_PER_TAP: "INCOME_PER_TAP",
        },
        HERO_RARITY: {
          ROOT: "HERO_RARITY",
          COMMON: "COMMON",
          RARE: "RARE",
          EPIC: "EPIC",
        },
      },
      HERO_NAMES: {
        ROOT: "HERO_NAMES",
        BAFFET: "BAFFET",
        BEARD: "BEARD",
        BEAST: "BEAST",
        BLONDE: "BLONDE",
        BOY: "BOY",
        BROWNHAIRED: "BROWNHAIRED",
        BUTEREN: "BUTEREN",
        CAPTAINAMERICA: "CAPTAINAMERICA",
        DEADPOOL: "DEADPOOL",
        DEFAULT: "DEFAULT",
        DEFAULTHQ: "DEFAULTHQ",
        DUROV: "DUROV",
        GIRL: "GIRL",
        GRETTATUMBERG: "GRETTATUMBERG",
        HASBIK: "HASBIK",
        IRONMAN: "IRONMAN",
        JONES: "JONES",
        MESSI: "MESSI",
        MUSK: "MUSK",
        OBGUY: "OBGUY",
        QUEEN: "QUEEN",
        REDHEAD: "REDHEAD",
        ROSSOMAHA: "ROSSOMAHA",
        SPIDERMAN: "SPIDERMAN",
        STRANGE: "STRANGE",
        TRUMP: "TRUMP",
        ZUCKERBERG: "ZUCKERBERG",
      },
    },
    SHOP: {
      ROOT: "SHOP",
      TITLE: "TITLE",
      KIT: "KIT",
      HAT: "HAT",
      CHAIN: "CHAIN",
      GLASS: "GLASS",
      WATCH: "WATCH",
      LABELS: {
        ROOT: "LABELS",
        BLOCKED: "BLOCKED",
        TOTAL: "TOTAL",
        CLOTH: {
          ROOT: "CLOTH",
          BAFFET: "BAFFET",
          BEARD: "BEARD",
          BEAST: "BEAST",
          BLONDE: "BLONDE",
          BOY: "BOY",
          BROWNHAIRED: "BROWNHAIRED",
          BUTEREN: "BUTEREN",
          CAPTAINAMERICA: "CAPTAINAMERICA",
          DEADPOOL: "DEADPOOL",
          DEFAULT: "DEFAULT",
          DEFAULTHQ: "DEFAULTHQ",
          DUROV: "DUROV",
          GIRL: "GIRL",
          GRETTATUMBERG: "GRETTATUMBERG",
          HASBIK: "HASBIK",
          IRONMAN: "IRONMAN",
          JONES: "JONES",
          MESSI: "MESSI",
          MUSK: "MUSK",
          OBGUY: "OBGUY",
          QUEEN: "QUEEN",
          REDHEAD: "REDHEAD",
          ROSSOMAHA: "ROSSOMAHA",
          SPIDERMAN: "SPIDERMAN",
          STRANGE: "STRANGE",
          TRUMP: "TRUMP",
          ZUCKERBERG: "ZUCKERBERG",
        },
      },
    },
    TOP_PLAYERS: {
      ROOT: "TOP_PLAYERS",
      TITLE: "TITLE",
      MENU_ITEMS: {
        ROOT: "MENU_ITEMS",
        LEAGUE: "LEAGUE",
        WORLD: "WORLD",
        FRIENDS: "FRIENDS",
      },
      TOURNAMENTS: {
        ROOT: "TOURNAMENTS",
        DIAMOND: "DIAMOND",
        DESCRIPTION: "DESCRIPTION",
      },
      BEST_PLAYERS: "BEST_PLAYERS",
      WINNERS: "WINNERS",
      LEAGUES: {
        ROOT: "LEAGUES",
        BRILLIANT: "BRILLIANT",
        GOLD: "GOLD",
        PLATINUM: "PLATINUM",
        BILLIARD: "BILLIARD",
        SILVER: "SILVER",
        BRONZE: "BRONZE",
      },
      MODAL: {
        ROOT: "MODAL",
        TITLE: "TITLE",
        DESCRIPTION: "DESCRIPTION",
        TOP: "TOP",
        BRILLIANT_LEAGUE: "BRILLIANT_LEAGUE",
        BRONZE_LEAGUE: "BRONZE_LEAGUE",
        SILVER_LEAGUE: "SILVER_LEAGUE",
        GOLD_LEAGUE: "GOLD_LEAGUE",
        PLATINUM_LEAGUE: "PLATINUM_LEAGUE",
        BILLIARD_LEAGUE: "BILLIARD_LEAGUE",
      },
    },
    BUY_STARS: {
      ROOT: "BUY_STARS",
      TITLE: "TITLE",
      DESCRIPTION: "DESCRIPTION",
      BUTTON_TEXT: "BUTTON_TEXT",
      WITHDRAW: "WITHDRAW",
      TOTAL_BALANCE: "TOTAL_BALANCE",
      AVAILABLE_TO_WITHDRAW: "AVAILABLE_TO_WITHDRAW",
      AVAILABLE_BALANCE: "AVAILABLE_BALANCE",
      AVAILABLE_BALANCE_DESCRIPTION: "AVAILABLE_BALANCE_DESCRIPTION",
      MODAL: {
        ROOT: "MODAL",
        TITLE: "TITLE",
        DESCRIPTION: "DESCRIPTION",
        BUTTON: "BUTTON",
      },
    },
    FORBIDDEN: {
      ROOT: "FORBIDDEN",
      TITLE: "TITLE",
      DESCRIPTION: "DESCRIPTION",
    },
  },
  ERRORS: {
    ROOT: "ERRORS",
  },
};
