export const NS = {
  COMMON: {
    ROOT: "COMMON",
    LOCALE_SWITCHER: {
      ROOT: "LOCALE_SWITCHER",
      RUSSIAN: "RUSSIAN",
      ENGLISH: "ENGLISH",
    },
    ROUTES: {
      ROOT: "ROUTES",
      SETTINGS: "SETTINGS",
    },
    TOAST: {
      ROOT: "TOAST",
      DESTRUCTIVE: "DESTRUCTIVE",
      DONE: "DONE",
      WARNING: "WARNING",
      UPDATE_TELEGRAM: "UPDATE_TELEGRAM",
    },
    OK: "OK",
  },
  PAGES: {
    SETTINGS: {
      ROOT: "SETTINGS",
      WALLET: {
        ROOT: "WALLET",
        TITLE: "TITLE",
        CONNECT_WALLET: "CONNECT",
      },
      BALANCE: {
        ROOT: "BALANCE",
        TITLE: "TITLE",
        STARS: "STARS",
        TON: "TON",
      },
      GENERAL_SETTINGS: {
        ROOT: "GENERAL_SETTINGS",
        TITLE: "TITLE",
        SOUND: "SOUND",
        VIBRATIONS: "VIBRATIONS",
      },
      ABOUT_THE_APP: {
        ROOT: "ABOUT_THE_APP",
        TITLE: "TITLE",
        RULES: "RULES",
        SUPPORT: "SUPPORT",
      },
      COMMUNITY: {
        ROOT: "COMMUNITY",
        TITLE: "TITLE",
        SUBSCRIBE: "SUBSCRIBE",
        LEARN_MORE: "LEARN_MORE",
      },
      LANGUAGE: {
        ROOT: "LANGUAGE",
        TITLE: "TITLE",
      },
      DISCONNECT_MODAL: {
        ROOT: "DISCONNECT_MODAL",
        TITLE: "TITLE",
        DESCRIPTION: "DESCRIPTION",
        AGGREEMENT: "AGGREEMENT",
        BUTTON: "BUTTON",
      },
    },
    ASSIGNMENTS: {
      ROOT: "ASSIGNMENTS",
      HEADER: {
        ROOT: "HEADER",
        BALANCE: {
          ROOT: "BALANCE",
          TITLE: "TITLE",
          STARS: "STARS",
          FRIENDS: "FRIENDS",
        },
      },
      TYPES: {
        ROOT: "TYPES",
        DAILY: "DAILY",
        ONE_OFF: "ONE_OFF",
      },
      MODALS: {
        ROOT: "MODALS",
        CHECK_ASSIGNMENTS: {
          ROOT: "CHECK_ASSIGNMENTS",
          DO_ASSIGNMENT: "DO_ASSIGNMENT",
          BUTTON: "BUTTON",
          SUBSCRIBE_TO_CHANNEL: "SUBSCRIBE_TO_CHANNEL",
          SHARE_STORY: "SHARE_STORY",
          ADD_GAME: "ADD_GAME",
          ADD_EMOJI_STATUS: "ADD_EMOJI_STATUS",
          BUY_STARS: "BUY_STARS",
          CHECK_ASSIGNMENTS: "CHECK_ASSIGNMENTS",
          WALLET_CONNECT: "WALLET_CONNECT",
          MAKE_TRANSACTION: "MAKE_TRANSACTION",
        },
        CONFIRMATION_MODAL: {
          ROOT: "CONFIRMATION_MODAL",
          TITLE: "TITLE",
          DESCRIPTION: "DESCRIPTION",
          AWARD: "AWARD",
          PENALTY: "PENALTY",
          BUTTON: "BUTTON",
          DOUBLE_CHECK: "DOUBLE_CHECK",
        },
      },
    },
    BATTLE_PASS: {
      ROOT: "BATTLE_PASS",
      BUTTONS: {
        ROOT: "BUTTONS",
        IMPROVE: "IMPROVE",
        COLLECT: "COLLECT",
      },
    },
    FRIENDS: {
      ROOT: "FRIENDS",
      TITLE: "TITLE",
      PROPOSAL: "PROPOSAL",
      INVITE_FRIEND: "INVITE_FRIEND",
      INVITE_DESCRIPTION: "INVITE_DESCRIPTION",
      INVITE_BUTTON_TEXT: "INVITE_BUTTON_TEXT",
      INVITED: "INVITED",
      COLLECT_PRIZE: "COLLECT_PRIZE",
      LINK_COPIED: "LINK_COPIED",
      PROFIT: "PROFIT",
      GET: "GET",
      GET_FRIENDS: "GET_FRIENDS",
      CAN_COLLECT: "CAN_COLLECT",
      MODAL: {
        ROOT: "MODAL",
        TITLE: "TITLE",
        DESCRIPTION: "DESCRIPTION",
        BUTTON: "BUTTON",
        SALE: "SALE",
        FRIENDS: "FRIENDS",
      },
    },
    REWARDS: {
      ROOT: "REWARDS",
      GET_REWARDS: "GET_REWARDS",
      TABS: {
        ROOT: "TABS",
        EARNINGS: "EARNINGS",
        REWARDS: "REWARDS",
        BOOSTERS: "BOOSTERS",
      },
    },
    HEROES: {
      ROOT: "HEROES",
      TITLE: "TITLE",
      TABS: {
        ROOT: "TABS",
        REGULAR: "REGULAR",
        RARE: "RARE",
        EPIC: "EPIC",
      },
    },
  },
};
