import { NS } from "@/constants/ns";
import FriendsSVG from "@/public/assets/svg/friends-coin.svg";
import StarSVG from "@/public/assets/svg/star.svg";
import { Currency, EventNames } from "@/services/rewards/types";

export const EVENTS_NAMES_TID: { [key in EventNames]: string } = {
  [EventNames.StarsBank]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.STARSBANK}`,
  [EventNames.OilCompany]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.OILCOMPANY}`,
  [EventNames.GreenEnergy]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.GREENENERGY}`,
  [EventNames.ChargingStation]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.CHARGINGSTATION}`,
  [EventNames.Psychologist]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.PSYCHOLOGIST}`,
  [EventNames.SuccessfulTrading]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.SUCCESSFULTRADING}`,
  [EventNames.Barbershop]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.BARBERSHOP}`,
  [EventNames.Streamer]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.STREAMER}`,
  [EventNames.ComputerClub]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.COMPUTERCLUB}`,
  [EventNames.GameCompany]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.GAMECOMPANY}`,
  [EventNames.Shop]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.SHOP}`,
  [EventNames.FoodDelivery]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.FOODDELIVERY}`,
  [EventNames.Restaurant]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.RESTAURANT}`,
  [EventNames.EducationalCourses]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.EDUCATIONALCOURSES}`,
  [EventNames.CyberSecurity]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.CYBERSECURITY}`,
  [EventNames.Starlink]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.STARLINK}`,
  [EventNames.Startup]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.STARTUP}`,
  [EventNames.ElecticalCommercy]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ELECTICALCOMMERCY}`,
  [EventNames.SocialNetworks]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.SOCIALNETWORKS}`,
  [EventNames.Blogging]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.BLOGGING}`,
  [EventNames.Podcaster]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.PODCASTER}`,
  [EventNames.OpinionLeader]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.OPINIONLEADER}`,
  [EventNames.Conference]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.CONFERENCE}`,
  [EventNames.Taxi]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.TAXI}`,
  [EventNames.Hotel]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.HOTEL}`,
  [EventNames.Autosalon]: `${NS.PAGES.REWARDS.EVENTS.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.ROOT}.${NS.PAGES.REWARDS.EVENTS.EVENTS_LIST.AUTOSALON}`,
};

export const PRICE_CURRENCY_ICON = {
  [Currency.COINS]: StarSVG,
  [Currency.FRIENDS]: FriendsSVG,
  [Currency.STARS]: StarSVG,
};
