export const BATTLE_PASS_BG_ASPECT_RATIO = 0.5625;
export const BATTLE_PASS_ROW_HEIGHT = 122;
export const BATTLE_PASS_LIST_PROGRESS_BAR_HEIGHT = 76;
export const BATTLE_PASS_BOTTOM_MENU_HEIGHT = 104;